# Generated by Django 5.1.3 on 2025-01-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_filler_product_fillers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fillers',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='catalog.filler'),
        ),
    ]
